version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: mysql_mcp_server
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mcp_server_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10
      timeout: 5s

  app:
    build: .
    container_name: mcp_server_app
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mcp_server_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    volumes:
      - ./src:/app/src         # Local src folder bind mount
      - ./target:/app/target   # Optional: compiled classes bind mount
    command: mvn spring-boot:run -Dspring-boot.run.fork=false
    restart: always
volumes:
   mysql_data:
