spring.application.name=mcp-server

server.port=8080

spring.datasource.url=jdbc:mysql://mysql:3306/mcp_server_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jira.api.url=https://ahirechetan291-1746419654842.atlassian.net/rest/api/3/issue
jira.api.email=ahirechetan291@gmail.com
jira.api.token=ATATT3xFfGF0RE0QLiSYnrAKxA8UnM7mAgkOhE86u2Zho5FJqYIRMgMTJaqg_lgE712Zml5QL_jRn6E_BBI11CmKJFpNgezgezC3Q-ouJ1vbQNlMK-h5W4aykM9xf6-CAy9g8r4rNEMtJ2u_rrGNTDRAuca28TtJq-jCyFOkxGW6_PPNI3gXkn8=48227FA1
jira.project.key=MS
abuseipdb.api.key=ce9da9b0aad90855261acb466f382a883dee1cc892c7b7a454645ac18c48410b7a12468692db90e1

# VirusTotal
virustotal.api.key=8c008f77b8a3275592d51c32ec0636432a0e03d58459bac53a8d14393660b1c9

# Google Safe Browsing
google.api.key=AIzaSyBXMri5tztXdZLygb9ZL_Fjm3u9E9-JoRQ



# Mail sender config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=itskpawar@gmail.com
spring.mail.password=ovxr ufcy tmzz wagg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Alert recipient
alert.email.to=kamleshpawar5278@gmail.com



management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
